[[redirects]]
  from = "/cv"
  to = "/"
  status = 301
  force = false
  query = {path = ":path"}

[[redirects]]
  from = "/about"
  to = "/"
  status = 301
  force = false
  query = {path = ":path"}

[[redirects]]
  from = "/projects"
  to = "/"
  status = 301
  force = false
  query = {path = ":path"}

[[redirects]]
  from = "/contact"
  to = "/"
  status = 301
  force = false
  query = {path = ":path"}    